apiVersion: networking.k8s.io/v1
kind: Ingress

metadata:
  name: {{ .Values.monitor.name }}-ingress
  namespace: {{ .Values.monitor.namespace }}

spec:
  ingressClassName: nginx

  rules:

    - host: cluster.prometheus
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: prometheus-kube-prometheus-prometheus
                port:
                  number: 9090

    - host: cluster.alertmanager
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: prometheus-kube-prometheus-alertmanager
                port:
                  number: 9093

    - host: cluster.grafana
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: prometheus-grafana
                port:
                  number: 80
