microservice:
  name: "frontend"
  namespace: "frontend"
  replicas: 1
  minReplicas: 1
  maxReplicas: 1
  revisionHistoryLimit: 5
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
container:
  name: "taskmanager-frontend"
  image: "congthanh19/taskmanager-frontend"
  tag: 1994744ebc283f80f74e5b2e6bf262661eded375
  imagePullPolicy: Always
workload:
  resources:
    limits:
      cpu: "500m"
      memory: "512Mi"
    requests:
      cpu: "250m"
      memory: "256Mi"
  livenessProbe:
    httpGet:
      path: /
      port: 3000
    initialDelaySeconds: 10
    periodSeconds: 10
    timeoutSeconds: 5
    failureThreshold: 3
  readinessProbe:
    httpGet:
      path: /
      port: 3000
    initialDelaySeconds: 10
    periodSeconds: 10
    timeoutSeconds: 5
    failureThreshold: 3
secret:
  name: frontend-secret
service:
  type: ClusterIP
  port: 3000
  targetPort: 3000


